.gitignore
code/subject_class.py

.gitignore was modified to include data/*
so, everyone can put ds105 folder under data/
without pushing them to github
Add code/subject_class.py
the goal for this piece of code is to organize the result from
same subject together. 
You are welcome to test the subject_class.
Set the /code directory as the working directory to test it.
The subject_class is still in progress.
Any suggestions are more than welcome!

Modify .gitignore and Add subject_calss.py

---

experimental/experiments.py

This folder will contain all our experimental code.

Creating experimental folder

---

how_to_obtain_data.txt

add Discusstion file oct.25

---

paper/project.bib
paper/report.tex

fixed report.bib
fixed report.tex

update report.tex draft2

---

paper/project.bib
paper/report.tex

Project and Report

---

how_to_obtain_data.txt

adding manually selected z values for subjects 1-6

Adding z values for subjects 1-6

---

paper/report.tex
requirements.txt

Hi folks, I have added nibabel to requirements.txt. 
it would be great if you could also check whats your versions are and lets all standardize our versions.

requirements.txt update

---

slides/progress.md

added content to progress.md

---

slides/progress.md

updates on progress.md

---

slides/progress.md

fixed typos and syntax in progress.md

fixed progress.md

---

data/data.py

Adding code to let the user know that hash code verification completes when "make validate" is run.

Added final verification statement at the end of make validate.

---

paper/report.tex

report.tex 80 char limit fixed.

report.tex fixed 80 character limit

---

experimental/testing_Jinnie_Mike_Edith_code.ipynb

adding loop

---

experimental/subject_class.py

Try this to see if it fixes the problem of "no such file or directory"

fix directory path problem

---

code/utils/maskfunc.py

Wrote a function to generate brain masks automatically

Created new mask function (collaborated with Mike)

---

code/utils/tests/test_affine.py

Just updated the tests for the real data. Still left it commented out for Travis CI.

Updating test_affine.py.

---

code/linear_model_scripts.py
code/utils/convolution.py
code/utils/get_object_neural.py
code/utils/linear_model.py
code/utils/maskfunc.py
code/utils/outlier.py
code/utils/smooth.py
code/utils/stimuli.py
code/utils/subject_class.py

I move most the the functions from experimental folder to code/utils.
Besides, I also include a script to run linear regression on sub001!

functions and scripts for linear model

---

code/linear_model_scripts_run1_3.py

Added a linear_model_scripts_run1_3.py file to compare correlations between faces and houses for runs 1 and 3

Adding a different linear model file

---

code/timeSeries.py

Time Series Analysis done for Sub1 Run1. Created an ACF & PACF of the time series, plot of the time series and the fitted model, residuals plot, and ACF & PACF of the residuals. Install statsmodel to run it

Time Series Analysis for Sub1 Run1

---

code/linear_model_scripts.py

There might be a merge conflict?

modify scripts to save each object/run as txt

---

slides/final.md

Made a .md template for final presentation and added most content

Added final presentation template

---

paper/project.bib
paper/report.tex

in this version of the report i have updated introduction and data. please fix the english and truncate the sentences if you got time cuz we will be having more juicy parts in the following sections of the report.

final report update 12-07-15

---

paper/corr_writeup.txt

Added a text file with the write-up for correlation analysis. Saved in a separate text file for easier review before adding it to the final report.

adding correlation write-up text file

---

experimental/beta_slice_index.txt

creating new txt file with indices for useful brain slices for subjects 2-6

adding indices for beta
